[network]
port = 37771
bootstraps = []
max_connections = 10
moniker = ""

[nostr]
port = 443
max_ws_connections = 100

[rpc]
enable_grpc = true
grpc_port = 9090

[metrics]
enable_metrics = false

[log]
write_to_file = true
path = "log.r7"
