name: Cargo Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get install protobuf-compiler
      - run: cargo test --all
      